In [1]:
# Day 3 – Session 35

## NumPy: Creating and Manipulating Arrays
#Topics covered:
#- Creating NumPy arrays
#- Basic array operations
#- Vectorized operations
#- Broadcasting


In [2]:
### Creating NumPy Arrays

In [3]:
import numpy as np

# From Python list
arr = np.array([1, 2, 3, 4])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((2, 3)))
print("Ones:", np.ones((2, 3)))

# Range
print("Arange:", np.arange(0, 10, 2))

# Random
print("Random:", np.random.rand(2, 2))

Array: [1 2 3 4]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Random: [[0.98251575 0.73023784]
 [0.07970173 0.04053353]]


In [4]:
### Vectorized Operations
#NumPy allows performing operations on arrays **element-wise** without explicit loops.

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square:", a ** 2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square: [1 4 9]


In [6]:
### Broadcasting
#Broadcasting allows NumPy to perform arithmetic between arrays of different shapes.

In [7]:
a = np.array([1, 2, 3])
print(a + 10)

matrix = np.ones((3,3))
print(matrix + a)

[11 12 13]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
